#!/usr/bin/env node
/**
 * Generate the assistant's face, once.
 *
 * A face is the one part of a human figure that procedural geometry cannot
 * reach. Lathed profiles give you a skull, a jaw and a silhouette; they do not
 * give you eyes, and at the size this figure stands on screen the difference
 * between "a head" and "a face" is entirely in the eyes.
 *
 * This project already knows how to make an image -- that is what it is for --
 * so the face is generated by the same model the assistant uses for everything
 * else, and cached to disk. Run once; committed nowhere; regenerate with
 * `npm run make:face -- --force` if you want a different one.
 *
 * The background must be pure black, not transparent: the figure is drawn
 * additively, so black composites to nothing on its own and no alpha channel
 * has to survive the round trip.
 *
 * Stdlib only, like every other script here.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const OUT = resolve(root, 'public/avatar/face.png');

const MODEL = process.env.GEMINI_IMAGE_MODEL ?? 'gemini-3.1-flash-image';
const API = 'https://generativelanguage.googleapis.com/v1beta/models';

/*
 * The framing matters more than the styling. The image is mapped onto a plane
 * the width of the skull, so the face has to fill the frame square-on and
 * symmetrically -- a three-quarter view or a head-and-shoulders crop lands the
 * eyes somewhere the geometry is not.
 *
 * Mouth closed, because the mouth is drawn separately and animated: a mouth in
 * the texture would sit there open behind the one that moves.
 */
const PROMPT = [
  'The face of a fictional female android, seen exactly front-on.',
  'Perfectly symmetrical, looking straight at the camera, eyes open, mouth closed and neutral.',
  'The face fills the frame from edge to edge: forehead at the top, chin at the bottom.',
  'Rendered as a holographic projection: luminous cyan and pale blue light, fine circuitry',
  'tracing the temples and cheekbones, smooth pale synthetic skin, bright cyan irises.',
  'Pure black background, no hair, no shoulders, no neck, no text, no watermark, no border.',
].join(' ');

function readKey() {
  if (process.env.GEMINI_API_KEY) return process.env.GEMINI_API_KEY;
  const envFile = resolve(root, '.env.local');
  if (!existsSync(envFile)) return null;
  const match = readFileSync(envFile, 'utf8').match(/^GEMINI_API_KEY=(.+)$/m);
  return match ? match[1].trim() : null;
}

async function main() {
  const force = process.argv.includes('--force');
  if (existsSync(OUT) && !force) {
    console.log(`face already generated: ${OUT}\n(pass --force to make a new one)`);
    return;
  }

  const key = readKey();
  if (!key) {
    console.error('GEMINI_API_KEY is not set, and no .env.local carries one.');
    console.error('The figure falls back to an abstract face without it -- this is optional.');
    process.exitCode = 1;
    return;
  }

  console.log(`asking ${MODEL} for a face...`);
  const response = await fetch(`${API}/${MODEL}:generateContent`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-goog-api-key': key },
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: PROMPT }] }],
      generationConfig: { responseModalities: ['IMAGE'], imageConfig: { imageSize: '1K' } },
    }),
  });

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    console.error(`image model returned ${response.status}: ${detail.slice(0, 300)}`);
    process.exitCode = 1;
    return;
  }

  const payload = await response.json();
  const candidate = payload.candidates?.[0];
  const inline = candidate?.content?.parts?.find((p) => p.inlineData)?.inlineData;
  if (!inline?.data) {
    console.error(`no image came back (${candidate?.finishReason ?? 'no reason given'})`);
    process.exitCode = 1;
    return;
  }

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, Buffer.from(inline.data, 'base64'));
  console.log(`wrote ${OUT}`);
}

main().catch((error) => {
  console.error(String(error));
  process.exitCode = 1;
});
